apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    type: web
spec:
  containers:
  - name: hello
    image: hello:v1
    imagePullPolicy: Never
    name: hello
    ports:
    - containerPort: 80
      protocol: TCP
