apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    type: web
spec:
  containers:
  - name: hello
    image: hello:v1
    imagePullPolicy: Never
    name: hello
    livenessProbe:
      exec:
        command:
        - ls
        - /tmp/
      initialDelaySeconds: 5
      periodSeconds: 5
    ports:
    - containerPort: 80
      protocol: TCP
